sudo: true
dist: xenial

git:
  depth: false

language: python

python:
  # - 2.7
  # - 3.5
  - 3.6
  # - 3.7

cache: pip

install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install pytest pytest-cov==2.5.1 pytest-pep8 coveralls

script:
  # - pytest --cov=deepcell_tracking --pep8
  - echo "Dummy Test"

jobs:
  include:
    - stage: deploy
    # if: tag IS present
      deploy:
        provider: pypi
        username: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        edge: true  # opt in to dpl v2
        on:
          branches:
            only:
              - willgraf/deploy

# after_success:
#   - coveralls
